### ISSUE TITLE
App Selector web browser view is black, CF my screenshot (on Windows ARM)

### ISSUE THREAD

**Issue by codebar33** [m-jishnu/alt-app-installer#27] opened 2023-01-29 18:53 UTC
Hi thanks for the app!

App Selector web browser view is black, CF my screenshot (on Windows ARM):
<img width="1294" alt="Screenshot 2023-01-29 at 19 51 14" src="https://user-images.githubusercontent.com/8226103/215349062-3f48bd67-a8e8-43e0-ac35-26b37a74287c.png">

**Comment by m-jishnu** [comment] 2023-01-30 05:46
Unfortunatly i dont own an ARM system therefore i cant reproduce this issue, so can you build it from source and tell me what it shows in console when the blackscreen occurs, it should provide some pointers on what is producing the issue

<img width="977" alt="image" src="https://user-images.githubusercontent.com/83004520/215396243-ff959673-3328-41f0-b25e-2b8b9b9ad47f.png">
 
The only temp fix i can provide is an option to download without using the app selector, you would need to manually go to [app.microsoft.com](https://apps.microsoft.com/) and get the url of the app that you want and paste it in a textbox then the app will do the rest.

**Comment by m-jishnu** [comment] 2023-01-30 13:06
I have implemented the option to install via link (Options --> Install From Link), check [v2.5.7](https://github.com/m-jishnu/alt-app-installer/releases/tag/v2.5.7). Btw the blackscreen issue is caused by some bug in qtwebengine so this should work, you would just need to manually get the url of the app you want and paste it in the text box. for fixing the blackscreen we need more info.

**Comment by codebar33** [comment] 2023-02-03 09:37
Thanks a lot @m-jishnu! I'll try to compile the project on Windows ARM when I have time but your workaround is already a great solution.

**Comment by m-jishnu** [comment] 2023-07-06 06:55
hello can you check the [v2.6.4](https://github.com/m-jishnu/alt-app-installer/releases/tag/v2.6.4) i have compiled it using latest pyqt web engine so it might fix the issue. In case it isn't fixed can you tell me what it shows in the console you don't need to build the app here is a debug version(v2.6.3):  https://www.mediafire.com/file/1f2tmg1eig354ll/alt+app+installer.exe/file . it will show a console so you can just use it directly.

**Comment by m-jishnu** [comment] 2023-08-08 17:32
closing this as it might be fixed and no further replies from the author, in case its not fixed feel free to re-open this issue

**Closed by m-jishnu** 2023-08-08 17:32 UTC
Labels: bug, question
